version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Installing PHP dependencies..."
      - composer install

  pre_build:
    commands:
      - echo "Preparing Laravel environment..."
      - cp .env.example .env
      - php artisan key:generate

  build:
    commands:
      - echo "Running tests..."
      - php artisan test

artifacts:
  files:
    - '**/*'
  discard-paths: yes
